name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-test-coverage
          path: coverage

      - name: Run Build
        if: github.event_name == 'push'
        run: npm run build

      - name: Upload Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

      - name: create a new Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release@5.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge ./build ${{ secrets.SURGE_STAGING_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
